import 'package:flutter/material.dart';

import '../../../../core/theme/app_spacing.dart';
import '../../../../core/theme/app_text_styles.dart';

enum LegalDocType { terms, privacy }

// Placeholder legal copy — not reviewed by counsel. Exists so the required
// acceptance checkbox on registration (owner request, 2026-08-14: "terms and
// privacy check should be on login screen or create an account too") links
// to real, readable content instead of a dead end. Replace with the actual
// Terms of Service / Privacy Policy before this app is submitted to a store
// or opened to real users.
const _termsBody = '''
Last updated: placeholder — replace before launch.

Medaculous is decision-support software for medical students and clinicians. It does not replace professional medical judgment, and content generated by Medaculous AI must always be verified against current local guidelines before acting on it.

By creating an account you agree to:
- Use the app only for lawful, professional, and educational purposes.
- Keep your account credentials confidential.
- Not attempt to extract, resell, or redistribute the app's content or AI responses as a commercial product.

Subscriptions (when available) renew automatically at the price shown at checkout until cancelled. You can cancel at any time from Settings.

This is placeholder text pending a full legal review.
''';

const _privacyBody = '''
Last updated: placeholder — replace before launch.

We store the account information you provide (email, display name, optional profile photo), your app content (notes, saved conversations, ward and exam-planner data), and basic usage metrics (AI message counts, used only to apply your plan's usage limit).

Your data is used to operate the app and is not sold to third parties. AI messages are sent to our language-model provider solely to generate a response and are not used to train shared models.

You can request account deletion at any time from Settings, which permanently removes your account and associated data.

This is placeholder text pending a full legal review.
''';

class LegalDocScreen extends StatelessWidget {
  const LegalDocScreen({super.key, required this.type});

  final LegalDocType type;

  @override
  Widget build(BuildContext context) {
    final isTerms = type == LegalDocType.terms;
    return Scaffold(
      appBar: AppBar(title: Text(isTerms ? 'Terms of Service' : 'Privacy Policy')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.xl),
          child: Text(isTerms ? _termsBody : _privacyBody, style: AppTextStyles.body),
        ),
      ),
    );
  }
}
